spring:
  graphql:
    path: /graphql
    websocket:
      path: /graphql # ws://localhost:8080/graphql
      connection-init-timeout: 60s # defines the WebSocket connection initialization timeout to 60 sec
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true
    cors:
      allowed-origins: '*'
      allowed-methods: 'GET,POST'
      max-age: '1800s'

#logging:
#  level:
#    root: INFO
#    graphql : TRACE
#    notprivacysafe : OFF

modbus:
  physicalDevice:
    # Every how many milliseconds must the system check if it needs to get new data from the physical devices.
    pollInterval: 500
